In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
dataset = pd.read_csv('/home/mahmoudahmad/IBM_AI_Engineering/projects/mobile_price/train.csv')

FileNotFoundError: [Errno 2] No such file or directory: '/home/mahmoudahmad/IBM_AI_Engineering/projects/mobile_price/train.csv'

In [ ]:
dataset.sample(5)

battery_power  blue  clock_speed  dual_sim  fc  four_g  int_memory  \
1611           1310     0          2.3         1   3       0          15   
821            1883     1          2.7         1   6       1          30   
1407           1617     0          1.5         0   1       1          63   
1832            897     0          1.4         1   1       0          17   
876            1064     0          2.9         1   1       1          34   

      m_dep  mobile_wt  n_cores  ...  px_height  px_width   ram  sc_h  sc_w  \
1611    0.2        150        5  ...        954       970  2518    18    17   
821     0.5         95        2  ...        531       791  3724    16    15   
1407    0.7        111        2  ...        274      1079  2754    19    10   
1832    0.4        171        1  ...        547      1852  2948    12     3   
876     0.2        184        6  ...       1175      1569   654    16    13   

      talk_time  three_g  touch_screen  wifi  price_range  
1611          5        0             1     1            2  
821          20        1             1     1            3  
1407          8        1             1     1            2  
1832          5        0             0     1            2  
876           6        1             0     0            0  

[5 rows x 21 columns]

In [ ]:
print('Check null')
dataset.isnull().sum()
print('='*10)
dataset.info()
dataset.describe()

Check null
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   battery_power  2000 non-null   int64  
 1   blue           2000 non-null   int64  
 2   clock_speed    2000 non-null   float64
 3   dual_sim       2000 non-null   int64  
 4   fc             2000 non-null   int64  
 5   four_g         2000 non-null   int64  
 6   int_memory     2000 non-null   int64  
 7   m_dep          2000 non-null   float64
 8   mobile_wt      2000 non-null   int64  
 9   n_cores        2000 non-null   int64  
 10  pc             2000 non-null   int64  
 11  px_height      2000 non-null   int64  
 12  px_width       2000 non-null   int64  
 13  ram            2000 non-null   int64  
 14  sc_h           2000 non-null   int64  
 15  sc_w           2000 non-null   int64  
 16  talk_time      2000 non-null   int64  
 17  three_g        2000 non-null   int64  
 1

battery_power       blue  clock_speed     dual_sim           fc  \
count    2000.000000  2000.0000  2000.000000  2000.000000  2000.000000   
mean     1238.518500     0.4950     1.522250     0.509500     4.309500   
std       439.418206     0.5001     0.816004     0.500035     4.341444   
min       501.000000     0.0000     0.500000     0.000000     0.000000   
25%       851.750000     0.0000     0.700000     0.000000     1.000000   
50%      1226.000000     0.0000     1.500000     1.000000     3.000000   
75%      1615.250000     1.0000     2.200000     1.000000     7.000000   
max      1998.000000     1.0000     3.000000     1.000000    19.000000   

            four_g   int_memory        m_dep    mobile_wt      n_cores  ...  \
count  2000.000000  2000.000000  2000.000000  2000.000000  2000.000000  ...   
mean      0.521500    32.046500     0.501750   140.249000     4.520500  ...   
std       0.499662    18.145715     0.288416    35.399655     2.287837  ...   
min       0.000000     2.000000     0.100000    80.000000     1.000000  ...   
25%       0.000000    16.000000     0.200000   109.000000     3.000000  ...   
50%       1.000000    32.000000     0.500000   141.000000     4.000000  ...   
75%       1.000000    48.000000     0.800000   170.000000     7.000000  ...   
max       1.000000    64.000000     1.000000   200.000000     8.000000  ...   

         px_height     px_width          ram         sc_h         sc_w  \
count  2000.000000  2000.000000  2000.000000  2000.000000  2000.000000   
mean    645.108000  1251.515500  2124.213000    12.306500     5.767000   
std     443.780811   432.199447  1084.732044     4.213245     4.356398   
min       0.000000   500.000000   256.000000     5.000000     0.000000   
25%     282.750000   874.750000  1207.500000     9.000000     2.000000   
50%     564.000000  1247.000000  2146.500000    12.000000     5.000000   
75%     947.250000  1633.000000  3064.500000    16.000000     9.000000   
max    1960.000000  1998.000000  3998.000000    19.000000    18.000000   

         talk_time      three_g  touch_screen         wifi  price_range  
count  2000.000000  2000.000000   2000.000000  2000.000000  2000.000000  
mean     11.011000     0.761500      0.503000     0.507000     1.500000  
std       5.463955     0.426273      0.500116     0.500076     1.118314  
min       2.000000     0.000000      0.000000     0.000000     0.000000  
25%       6.000000     1.000000      0.000000     0.000000     0.750000  
50%      11.000000     1.000000      1.000000     1.000000     1.500000  
75%      16.000000     1.000000      1.000000     1.000000     2.250000  
max      20.000000     1.000000      1.000000     1.000000     3.000000  

[8 rows x 21 columns]

In [ ]:
dataset

In [ ]:
dataset.corr()['price_range']

battery_power    0.200723
blue             0.020573
clock_speed     -0.006606
dual_sim         0.017444
fc               0.021998
four_g           0.014772
int_memory       0.044435
m_dep            0.000853
mobile_wt       -0.030302
n_cores          0.004399
pc               0.033599
px_height        0.148858
px_width         0.165818
ram              0.917046
sc_h             0.022986
sc_w             0.038711
talk_time        0.021859
three_g          0.023611
touch_screen    -0.030411
wifi             0.018785
price_range      1.000000
Name: price_range, dtype: float64

In [ ]:
X = dataset.iloc[: , :-1]
y = dataset.iloc[:, -1]

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [ ]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.multiclass import OneVsOneClassifier
from sklearn.neighbors import KNeighborsClassifier
model = OneVsOneClassifier(LogisticRegression(max_iter=1000))
model.fit(X_train_scaled,y_train)
# accuracy = 0.9775 

# from sklearn.tree import DecisionTreeClassifier
# decision_tree_classifier = DecisionTreeClassifier(criterion='entropy',max_depth=4)
# model = decision_tree_classifier.fit(X_train_scaled,y_train)
# accuracy = 0.7925

# knn_classifier = KNeighborsClassifier(n_neighbors=4)
# model = knn_classifier.fit(X_train_scaled,y_train)
# accurcay = 0.495

OneVsOneClassifier(estimator=LogisticRegression(max_iter=1000))

In [ ]:
y_pred = model.predict(X_test_scaled)
from sklearn.metrics import confusion_matrix,accuracy_score
cm = confusion_matrix(y_test,y_pred)
print(cm)
accuracy_score(y_test,y_pred)

[[101   4   0   0]
 [  0  91   0   0]
 [  0   2  88   2]
 [  0   0   1 111]]


0.9775